# Use the official Python lightweight image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Install required system dependencies for psycopg2-binary
RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*

# Copy the requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application source code
COPY main.py .

# Command to execute the Consumer application
CMD ["python", "main.py"]